export const DEV_GOOGLE_SHEETS_DATA = [
  [
    'Timestamp',
    'Email',
    'Name',
    'Mexico - Sør-Afrika',
    'USA - Norge',
    'Hvem går videre til 16-delsfinaler?',
    'Hvilke lag finner vi i semifinalene?',
    'Vinner',
    'Toppscorer etter gruppespill',
    'Hvem skårer Norges første mål?',
  ],
  [
    '2026-06-01 18:00:00',
    'anna@example.com',
    'Anna',
    '2-1',
    '1-2',
    'Argentina, Brasil, Frankrike, Norge',
    'Frankrike, Spania, Brasil, Argentina',
    'Frankrike',
    'Håland',
    'Håland',
  ],
  [
    '2026-06-01 18:03:00',
    'bjorn@example.com',
    'Bjørn',
    '2-0',
    '1-1',
    'Argentina, Tyskland, Spania, Norge',
    'Frankrike, England, Brasil, Portugal',
    'Brasil',
    'Mbappe',
    'Ødegaard',
  ],
  [
    '2026-06-01 18:06:00',
    'carla@example.com',
    'Carla',
    '0-0',
    '0-2',
    'Japan, Brasil, Frankrike, Danmark',
    'Spania, Argentina, Nederland, Tyskland',
    'Spania',
    'Haaland',
    'Håland',
  ],
  [
    'fasit',
    '',
    '',
    '2-1',
    '',
    'Argentina, Brasil, Frankrike, Norge',
    '',
    'Frankrike',
    '',
    'Håland',
  ],
];
